# Generated by Django 5.0.7 on 2024-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('one-time', 'One-time Expense'), ('fixed', 'Fixed Expense')], default='one-time', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='one-time', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('one-time', 'One-time Income'), ('recurring', 'Recurring Income')], default='one-time', max_length=10),
        ),
    ]
